### ISSUE TITLE
기능 요청_FAQ 컨텐츠 

### ISSUE THREAD

**Issue by tesla1220** [k-mcp/My_Class_Planner#25]
**기능에 문제가 있나요?**
- 관리자에게만 보여지는 FAQ 페이지 생성 완료
- FAQ 컨텐츠를  웹사이트 어디에 배치해야할 지 논의 필요

**해결책**
1) 홈 화면에 How to use 버튼을 추가해 클릭 시 FAQ 화면이 나타나게 함
2) FAQ 컨텐츠를 Contact Us 에 합병 ▶ 이 경우 Contact Us에 에 있던 입력칸들의 위치를 다시 재배열해야하므로 디자인 논의 필요

**다른 해결책**
FAQ 배치에 관해 자유롭게 의견 주세요!

**Comment by Leeeunsookl** [comment]
관리자가 community 글 삭제할 수 있고 FAQ 등록, 수정, 삭제 할 수 있는 권한 추가
