### ISSUE TITLE
기능 요청 CSS 디자인 통일

### ISSUE THREAD

**Issue by Leeeunsookl** [k-mcp/My_Class_Planner#29]
**기능에 문제가 있나요?**
CSS 폰트 전체 수정 및 색 통일, 디자인 통일 추가
CSS 폰트가 전체에 안먹는 중

**해결책**
CSS style 심기

**다른 해결책**
html에 직접 !important 적용해보기

**추가 사항**
프론트 개선이 부족할 경우 피그마로 재논의할 예정

**Comment by tesla1220** [comment]
전체 폰트 통일 완료
