### ISSUE TITLE
기능 요청_Settings: Update User Information 

### ISSUE THREAD

**Issue by tesla1220** [k-mcp/My_Class_Planner#40]
**기능에 문제가 있나요?**
Setting 페이지 내 Update User Information 기능 구현 필요 

**해결책**
해당 기능 구현

**Comment by tesla1220** [comment]
1) 프로필 사진 -> 회원 등급별 아이콘으로 대체
2) 회원 등급은 Generate 이용 빈도로 나뉨
3) 등급 아이콘은 Community 내 글 작성 시 username 옆에 반영

**Comment by Leeeunsookl** [comment]
프로필 사진 완료
